TradingView/TradingView/Pages/XETR/DAX.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using TradingView.Models;

namespace TradingView.Pages.XETR
{
    public class DAXModel : PageModel
    {
        private UserContext db;

        private Subscription sub;
        public DAXModel(UserContext _db)
        {
            db = _db;
        }
        public void OnGet()
        {
        }
        public void OnGetSubscribe()
        {
            User user = db.Users.FirstOrDefault(u => u.Username == User.Identity.Name);
            if (db.Subscriptions.FirstOrDefault(s => s.User == user && s.Name == "DAX" && s.Exchange == "XETR") == null)
            {
                sub = new Subscription();
                sub.User = user;
                sub.Name = "DAX";
                sub.Exchange = "XETR";
                db.Subscriptions.Add(sub);
                db.SaveChanges();
            }
            else
            {
                db.Subscriptions.Remove(db.Subscriptions.FirstOrDefault(s => s.User == user && s.Name == "DAX" && s.Exchange == "XETR"));
                db.SaveChanges();
            }
        }
        public async Task<IActionResult> OnGetLogout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToPage("Index");
        }
    }
}

TradingView/TradingView/Pages/XETR/DAX.cshtml
@page
@model TradingView.Pages.XETR.DAXModel
@{
}

<head>
    <link href="~/css/trading2.css" rel="stylesheet" />
</head>

@if (User.Identity.IsAuthenticated)
{
    <div id="sub"><a class="btn btn-outline-primary" asp-page-handler="Subscribe">Подписаться</a></div>
}

<!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container">
    <div id="tradingview_abbc4"></div>
    <div class="tradingview-widget-copyright"><a href="https://ru.tradingview.com/symbols/XETR-DAX/" rel="noopener" target="_blank"><span class="blue-text">График DAX</span></a> от TradingView</div>
    <script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>
    <script type="text/javascript">
        new TradingView.widget(
            {
                "width": 980,
                "height": 610,
                "symbol": "XETR:DAX",
                "interval": "D",
                "timezone": "Etc/UTC",
                "theme": "light",
                "style": "3",
                "locale": "ru",
                "toolbar_bg": "#f1f3f6",
                "enable_publishing": false,
                "allow_symbol_change": true,
                "container_id": "tradingview_abbc4"
            }
        );
    </script>
</div>
<!-- TradingView Widget END -->
<!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container" id="analysis">
    <div class="tradingview-widget-container__widget"></div>
    <div class="tradingview-widget-copyright"><a href="https://ru.tradingview.com/symbols/TVC-DEU30/technicals/" rel="noopener" target="_blank"><span class="blue-text">Технический анализ DEU30</span></a> от TradingView</div>
    <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-technical-analysis.js" async>
        {
            "interval": "1m",
                "width": "480",
                    "isTransparent": false,
                        "height": "450",
                            "symbol": "TVC:DEU30",
                                "showIntervalTabs": true,
                                    "locale": "ru",
                                        "colorTheme": "light"
        }
    </script>
</div>
<!-- TradingView Widget END -->
<!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container" id="cprofile">
    <div class="tradingview-widget-container__widget"></div>
    <div class="tradingview-widget-copyright"><a href="https://ru.tradingview.com/symbols/XETR-DAX/" rel="noopener" target="_blank"><span class="blue-text">Профиль DAX</span></a> от TradingView</div>
    <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-symbol-profile.js" async>
        {
            "symbol": "XETR:DAX",
                "width": 480,
                    "height": 650,
                        "colorTheme": "light",
                            "isTransparent": false,
                                "locale": "ru"
        }
    </script>
</div>
<!-- TradingView Widget END -->